version: 2
updates:
  # Fetch and update latest `npm` packages
  - package-ecosystem: npm
    directory: "/web"
    schedule:
      interval: monthly
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - AchoArnold
    assignees:
      - AchoArnold
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
  # Fetch and update latest `npm` packages
  - package-ecosystem: npm
    directory: "/widget"
    schedule:
      interval: monthly
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - AchoArnold
    assignees:
      - AchoArnold
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
  # Fetch and update latest `go` packages
  - package-ecosystem: gomod
    directory: "/api"
    schedule:
      interval: weekly
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - AchoArnold
    assignees:
      - AchoArnold
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
  # Fetch and update latest `npm` packages
  - package-ecosystem: npm
    directory: "/website"
    schedule:
      interval: monthly
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - AchoArnold
    assignees:
      - AchoArnold
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - AchoArnold
    assignees:
      - AchoArnold
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
