repos:
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: master
    hooks:
      - id: go-fumpt
      - id: go-mod-tidy
      - id: go-imports
      - id: go-staticcheck-mod

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: main
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: main
    hooks:
      - id: eslint
        files: (\.[jt]s)|(\.vue)$
        types: [file]
